
#------------------------------------------------------------------------------- 
# Raspberry Pi Zero - CPU Load
#------------------------------------------------------------------------------- 
Target[rpizero-cpu]: 100 - 1.3.6.1.4.1.2021.11.11.0&1.3.6.1.4.1.2021.11.11.0:public@localhost
MaxBytes[rpizero-cpu]: 100
YLegend[rpizero-cpu]: CPU %
ShortLegend[rpizero-cpu]: %
LegendI[rpizero-cpu]: CPU
Legend1[rpizero-cpu]: CPU usage
Options[rpizero-cpu]: integer, gauge, nopercent, growright, unknaszero, noo
Title[rpizero-cpu]: CPU load
PageTop[rpizero-cpu]: <H2>CPU load</H2>

#------------------------------------------------------------------------------- 
# RPi Zero Memory Load
#------------------------------------------------------------------------------- 
